# Archivo Docker Compose para múltiples réplicas con balanceo de carga

# Definición de replicas de servicios y redes 
services:
  # Frontend services
  frontend1:
    image: rodrigoalonsocl/sigphe-app_frontend:latest
    networks:
      - frontend-network

  frontend2:
    image: rodrigoalonsocl/sigphe-app_frontend:latest
    networks:
      - frontend-network

  frontend3:
    image: rodrigoalonsocl/sigphe-app_frontend:latest
    networks:
      - frontend-network

  # Backend services
  backend1:
    image: rodrigoalonsocl/sigphe-app_backend:latest
    environment:
      - DB_HOST=192.168.1.11
      - TZ=America/Santiago
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE=America/Santiago
      - SPRING_JACKSON_TIME_ZONE=America/Santiago
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend-network

  backend2:
    image: rodrigoalonsocl/sigphe-app_backend:latest
    environment:
      - DB_HOST=192.168.1.11
      - TZ=America/Santiago
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE=America/Santiago
      - SPRING_JACKSON_TIME_ZONE=America/Santiago
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend-network

  backend3:
    image: rodrigoalonsocl/sigphe-app_backend:latest
    environment:
      - DB_HOST=192.168.1.11
      - TZ=America/Santiago
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE=America/Santiago
      - SPRING_JACKSON_TIME_ZONE=America/Santiago
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend-network

  # Nginx balanceo de carga del frontend
  nginx-frontend:
    image: nginx:latest
    ports:
      - "8070:80"
    volumes: # Conecta el archivo de configuración personalizado con el archivo de configuración de Nginx dentro del contenedor
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  # Nginx balanceo de carga del backend
  nginx-backend:
    image: nginx:latest
    ports:
      - "8090:8090"
    volumes: 
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network: